version: '3.9'

services:

#--------------------------------------- nginx

  nginx:
    image: nginx:1337
    build: ./requirements/nginx/
    container_name: nginx
    volumes:
      - wordpress-vol:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

#--------------------------------------- mariadb

  mariadb:
    image: mariadb:1337
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb-vol:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
    restart: always

#--------------------------------------- wordpress
  wordpress:
    image: wordpress:1337
    build: ./requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress-vol:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

#----------------------------------------
volumes:
  wordpress-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/data/wordpress-volume"
  mariadb-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/data/mariadb-volume"

networks:
  inception:
    name: inception